#!/usr/bin/env bash

set -e

statefile='/var/cache/ipv6-check/ipv6-check.state'
recipients='root'
host='google.de'
timeout=30

opt=
while getopts ':s:h:r:t:' opt; do
  case "$opt" in
    s)
      statefile="$OPTARG"
      ;;

    h)
      host="$OPTARG"
      ;;

    r)
      recipients="$OPTARG"
      ;;

    t)
      timeout="$OPTARG"
      ;;

    '?')
      printf 'Invalid option: -%s\n' "$OPTARG"

      usage=$(cat <<EOF
%s [-s STATEFILE] [-h HOST] [-r RECIPIENTS] [-t TIMEOUT]

Check IPv6 connectivity by pinging a host, and optionally send email on connectivity change.

Options:
-s\tSpecify state file, default: $statefile
-h\tSpecify host to ping, default: $host
-r\tSpace-separated list of email recipients, default: $recipients
-t\tTime in minutes to wait before sending notification after IPv6 becomes unreachble, default: $timeout
EOF
)

      printf "$usage\n" "${0##*/}"
      exit 1
      ;;
  esac
done

mkdir --parents "$(dirname "$statefile")"

if [[ -f "$statefile" ]]; then
  contents=($(< "$statefile"))
  laststate="${contents[0]}"
  timestamp=$((${contents[1]-0}))
fi

now=$(("$(date --utc +%s)"))

notify() {
  [[ -n "$recipients" && \
     "$laststate" == '' || \
     (
       "$laststate" == 'down' && \
       $((now - timestamp)) > $((timeout * 60))
     )
  ]]
}

send-email() {
  MAILRC=/dev/null echo "$message" | \
    mail -n -s "IPv6 check on $(hostname)" $recipients
}

if ping -6 -c 1 "$host"; then
  exit_status=0

  if [[ "$laststate" != 'up' ]]; then
    printf 'up %s' "$now" > "$statefile"
  fi

  message=$(printf '%s is reachable\n' "$host")
  echo "$message"

  if notify; then
    send-email
  fi
else
  exit_status=2

  if [[ "$laststate" != down* ]]; then
    printf 'down %s' "$now" > "$statefile"
    exit_status=1
  fi

  message=$(printf '%s is not reachable\n' "$host")
  >&2 echo "$message"

  if notify; then
    send-email

    [[ "$laststate" == '' ]] && ts="$now" || ts="$timestamp"
    printf 'down-notified %s' "$ts" > "$statefile"
  fi
fi

exit $exit_status
